#+TITLE: jabber.el
#+SUBTITLE: XMPP client for Emacs
#+DESCRIPTION: Documentation

* Introduction
:PROPERTIES:
:CUSTOM_ID: introduction
:END:
This is jabber.el 0.8.92, an XMPP client for Emacs.  XMPP (also known as 'Jabber') is an instant messaging system; see http://xmpp.org for more information.

New resources
+ [[https://tildegit.org/wgreenhouse/emacs-jabber/][project page]]
+ chat: [[xmpp:emacs@salas.suchat.org?join][xmpp:emacs@salas.suchat.org?join]]

Old resources
+ [[http://sourceforge.net/projects/emacs-jabber][project page]]
+ [[http://emacs-jabber.sourceforge.net][home page]]
+ [[http://www.emacswiki.org/cgi-bin/wiki/JabberEl][wiki page]]
+ mailing list:
  * http://lists.sourceforge.net/lists/listinfo/emacs-jabber-general
  * http://dir.gmane.org/gmane.emacs.jabber.general
+ chat: jabber.el@conference.jabber.se and emacs@conference.jabber.ru (Russian, English)

** GNU Emacs
jabber.el runs on GNU Emacs 23.1 or later.

The file hexrgb.el (http://www.emacswiki.org/emacs/hexrgb.el) is needed for MUC nick coloring feature.  A copy is located in the compat directory, and used if the configure script doesn't find another copy already installed.

** XEmacs
You need an XEmacs with Mule support, and recent versions of the gnus, net-utils and mule-ucs packages.  jabber.el basically works on XEmacs, but some features are missing (in particular mouse support).  Testing and patches are very welcome.

** Encrypted connections
Many Jabber servers require encrypted connections, and even if yours doesn't it may be good idea.  To get an encrypted connection, the most convenient option is to use GNU Emacs 24 with GnuTLS support compiled in.  You can check whether you have that by typing:

: M-: (gnutls-available-p)

If that commands shows =t= in the echo area, then you have working GnuTLS support.  If it shows =nil= or signals an error, then you don't.

Failing that, jabber.el will use the starttls.el library, which requires that the GnuTLS command line tool "gnutls-cli" is installed.

In Debian-based distributions, "gnutls-cli" is in the "gnutls-bin" package.

The above applies to STARTTLS connections, the most common way to encrypt a Jabber connection and the only one specified in the standards.  STARTTLS connections start out unencrypted, but switch to encrypted after negotiation.  jabber.el also supports connections that are encrypted from start.  For this it uses the tls.el library, which requires either "gnutls-cli" or the OpenSSL command line tool "openssl" to be installed.

To use the latter form of encryption, customize =jabber-account-list=.

Note that only the connection from you to the server is encrypted; there is no guarantee of connections from your server to your contacts' server being encrypted.

** Usage
To connect to a Jabber server, type =C-x C-j C-c= (or equivalently =M-x jabber-connect-all=) and enter your JID.  With prefix argument, register a new account.  You can set your JID permanently with =M-x jabber-customize=.

Your roster is displayed in a buffer called *-jabber-*.  To disconnect, type =C-x C-j C-d= or =M-x jabber-disconnect=.

You may want to use the menu bar to execute Jabber commands.  To enable the Jabber menu, type =M-x jabber-menu=.

For a less terse description, read the enclosed manual.

For bug reports, help requests and other feedback, use the trackers and forums at the project page mentioned above.

** Configuration
All available configuration options are described in the manual.  This section only serves to point out the most important ones.

To change how you are notified about incoming events, type =M-x customize-group RET jabber-alerts=.

To activate logging of all chats, set =jabber-history-enabled= to =t=.  By default, history will be saved in =~/.jabber_global_message_log=; make sure that this file has appropriate permissions.  Type =M-x customize-group RET jabber-history= for more options.

By default, jabber.el will send a confirmation when messages sent to you are delivered and displayed, and also send "contact is typing" notifications.  To change this, type =M-x customize-group RET jabber-events=, and set the three =jabber-events-confirm-*= variables to nil.

** File transfer
This release of jabber.el contains support for file transfer.  You may need to configure some variables to make it work; see the manual for details.

** XMPP URIs
It is possible to make various web browsers pass links starting with "xmpp:" to jabber.el.  In the ideal case, this works right after running "make install".  Otherwise, see the manual, section "XMPP URIs".

* Getting started
:PROPERTIES:
:CUSTOM_ID: getting-started
:END:
** Installation
jabber.el can be installed using the commands:
#+BEGIN_SRC shell :tangle no :load no
./configure
make
make install
#+END_SRC

You can specify which emacs you want to use:
: ./configure EMACS=emacs-or-xemacs-21.4

You can also install jabber.el by hand.  Put all .el files somewhere in your =load-path=, or have your =load-path= include the directory they're in.  To install the Info documentation, copy =jabber.info= to =/usr/local/info= and run ="install-info /usr/local/info/jabber.info"=.

After installation by either method, add (load "jabber-autoloads") to your .emacs file.  (If you got the code from GIT, you still need the makefile to generate jabber-autoloads.el.)

If you are upgrading from 0.7-0.7.x, you need to update your configuration.  See the section "Account settings" in the manual.

*** Special notes for Git version
If you are running jabber.el from Git, you need to generate the =jabber-autoloads.el= file yourself.  The simplest way to do this is by using the =./configure && make= process.

To generate the configure script, make sure that autoconf and automake are installed and run =autoreconf -i=.

** [Developers] Making your first pull request
:PROPERTIES:
:CUSTOM_ID: getting-started-dev
:END:
1. Clone the jabber.el repository.
   #+BEGIN_SRC shell :tangle no
     mkdir ~/git/ && cd ~/git/
     git clone https://tildegit.org/wgreenhouse/emacs-jabber
   #+END_SRC
2. Install development dependencies.
   1. Install Org mode v9.3.8 or higher.
      #+BEGIN_SRC shell :tangle no
        git clone https://code.orgmode.org/bzg/org-mode.git
        cd ~/git/org-mode/
        make
      #+END_SRC
   2. Install Magit - type -
      #+BEGIN_SRC
        M-x package-install RET magit RET
      #+END_SRC
      or evaluate -
      #+BEGIN_SRC emacs-lisp :tangle no :load no
        (package-install 'magit)
      #+END_SRC
   3. Install the remaining tools.
      #+BEGIN_SRC shell :tangle no
        cd ~/git/emacs-jabber/
        make -f contrapunctus.mk setup
      #+END_SRC
3. Set up automatic tangling, linting, and testing - in the =emacs-jabber= directory, create a =.dir-locals-2.el= containing the following -
   #+BEGIN_SRC emacs-lisp :tangle no :load no
((org-mode . ((nameless-mode . t)
              (eval . (progn
                        (make-local-variable 'after-save-hook)
                        (add-hook 'after-save-hook
                                  (lambda ()
                                    (compile
                                     (concat
                                      "make ORG_PATH=\"~/git/org-mode/lisp/\" "
                                      "--silent --always-make "
                                      "-f contrapunctus.mk "
                                      "tangle")))
                                  nil t)))
              ;; use `vc-before-checkin-hook' instead, if using `vc'
              (eval . (add-hook 'magit-post-stage-hook
                                (lambda ()
                                  ;; check if we are in the right project
                                  (when (file-exists-p "jabber.org")
                                    (compile
                                     (concat
                                      "make --silent --always-make "
                                      "-f contrapunctus.mk lint")))))))))
   #+END_SRC
   Note -
   * =ORG_PATH= must point to the =/lisp/= subdirectory of the cloned Org repository.
   * =.dir-locals-2.el= is for your personal preferences - do not add it to the repository.
4. Create your branch, and open =jabber.org= for editing. Press =!= to accept the directory local variables, then make your changes. Always edit =jabber.org=, never =jabber.el=!
5. Stage your changes in =jabber.org=, as well as the changes in the automatically tangled sources in =jabber.el=.
6. Address the issues presented by the linters and tests. Hitting Enter on an error in the compilation buffer will take you to the source in =jabber.el= - use =org-babel-tangle-jump-to-org= to go to the source block in =jabber.org=.
7. Push and create your PR, or send a patch using [[https://git-send-email.io/][=git-send-email=]] to wgreenhouse@tilde.club

* TODO maintenance [0%]
1. [ ] Satisfy =M-x checkdoc=
2. [ ] Use =rx= where regular expressions get hairy
   * [ ] =jabber-jid-username=
   * [ ] =jabber-jid-server=
   * [ ] =jabber-jid-resource=
3. [ ] hexrgb.el is not available on MELPA
4. [ ] Migrate tests to ERT/Buttercup/etc
5. [ ] Add Windows support to developer tutorial
6. [ ] Create testing for tutorial

* Explanation
:PROPERTIES:
:CUSTOM_ID: explanation
:END:

** About this file
jabber.el is an Org literate program. Tangling is done automatically after each save.

Alternatively, it is possible to use =literate-elisp-load= from  [[https://github.com/jingtaozf/literate-elisp][literate-elisp]] to directly load this Org file. This way, links to the source (e.g. =describe-*= buffers, byte-compilation messages) take the user directly to the Org file rather than to the tangled source.

If a source block does not have syntax highlighting, press =M-o M-o= (=font-lock-fontify-block=) in it.

*** TODO literate/organizational tasks [25%]
1. [ ] (maybe) make dependencies optional and tangle them to separate files, reducing load time for users.
2. [ ] contemplate [[https://github.com/melpa/melpa/issues/7408][distribution strategies]]
3. [ ] make headings for remaining definitions - some FSM-related definitions remain.
4. [ ] move tests to this file (probably migrate them to =ert= or =buttercup= first), in sub-headings of their concerned components.
5. [ ] move dependencies to the Dependencies heading; also make library headers for them
6. [X] move per-file author information and copyright notice here, and delete the empty .el files
   * But it will cease to remain applicable as soon as we move anything around...
7. [ ] "Code" has a lot of direct sub-headings, making it somewhat cumbersome to navigate; someone with a better understanding of the program could organize these better
8. [X] The tangled file currently does not list all the other authors (currently listed in =:COPYRIGHT:= drawers). We could add them all at once in the library headers section...or something else. 🤔

* Credits
** Developers
+ Tom Berger
+ Magnus Henoch
+ Kirill A. Korinskiy
+ Detlev Zundel
  - wmii support
+ Evgenii Terechkov

** Contributors
+ Georg Lehner
  - network transport functions
+ Anthony Chaumas-Pellet
+ Jérémy Compostella
+ Mathias Dahl
  - history logging
  - watch functionality
+ Mario Domenech Goulart
  - sawfish support
  - xmessage support
+ Nolan Eakins
+ Ami Fischman
  - Chat State Notifications
+ François Fleuret
+ David Hansen
+ Adam Sjøgren
  - notifications.el support
+ Rodrigo Lazo
  - notifications.el support
  - libnotify.el support
+ Justin Kirby
+ Carl Henrik Lunde
  - network transport functions
  - activity tracking
+ Olivier Ramonat
+ Andrey Slusar
+ Valery V. Vorotyntsev
  - GMail notifications
+ Milan Zamazal
+ Xavier Maillard
+ Vitaly Mayatskikh
+ Alexander Solovyov
+ Demyan Rogozhin
  - XML console mode
+ Michael Cardell Widerkrantz
  - tmux support

** Maintainers
+ wgreenhouse
  - 2021 resurrection
+ contrapunctus
  - literate Org migration
  - Makefile
+ tomasino on #team@irc.tilde.chat
  - helping contrapunctus debug the Makefile
